[project]
name = "fanda"
version = "0.1.0"
description = "Figures and Axes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "scienceplots>=2.2.0",
    "seaborn>=0.13.2",
    "wandb>=0.23.0",
]
